### ISSUE TITLE
✨ test: develop 브랜치 빌드 테스트

### ISSUE THREAD

**Issue by hnnynh** [KTB-6-Joing/joing-server#14]
## 어떤 기능인가요?
develop 브랜치에서 GitHub Actions으로 빌드 테스트를 진행하고 
main 브랜치는 젠킨스에서 프로덕션 이미지 빌드용으로만 사용하려고 합니다.

<br/>

## 작업 상세 내용

- [x] GitHub Action 설정
- main branch merge 제한 (보류)

<br/>

**Comment by konempty** [comment]
@hnnynh 
이번 프로젝트에서 작업관리에 지라를 쓰고 계시는 만큼
요런 이슈와 할일 관리는 깃헙 이슈 기능을 사용하시는것 보다는
지라에 티켓을 따서 관리하는게 일관적이고 편하게 관리가 가능할것 같아요!
